name: mesa_ventas_mobile
description: Aplicación privada de ventas conectada al Worker de Cloudflare.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.14.1
  share_plus: ^13.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
